### ISSUE TITLE
Temper1 no longer for sale. Does this work with Temper2?

### ISSUE THREAD

**Issue by rjsteinert** [asmuelle/node-temper1#6]
Hi there, I've got this open source greenhouse alert project going called [Fido](http://farmhack.net/tools/fido-temperature-alarm-sends-text-messages) and I'm sorry to say that Temper1 supply is dwindling. I'm wondering how well this driver works with Temper2 sensors. You wouldn't happen to have tried them would you have?

**Comment by asmuelle** [comment]
Hi, sorry for the late reply. Unfortunately I have no temper2 device for testing.
